// Code generated by go run -tags generate pause_pubkey_gen.go # DO NOT EDIT.

package CPAN

import (
	"crypto/dsa"
	"math/big"
	"time"

	"golang.org/x/crypto/openpgp/packet"
)

// PAUSEPublicKey is the embeded public key of the central PAUSE indexer
var PAUSEPublicKey *packet.PublicKey

func init() {
	var dsaPubKey dsa.PublicKey
	dsaPubKey.P, _ = new(big.Int).SetString("vvcmhykpch3ecutekargc8il3ylj8jhwdg5zpp4rta1p5bq5m6ksst42mp3vz2fgjgyx972tn1t230q9fhn8df67cg5ax1de4n57twa91n1y9ykx237pz8jbha697207fheuhn22y6rkqla89x355laa5qblyjalroq590nxiq5yqef4ojryiisvhdq36ghlijrwob", 36)
	dsaPubKey.Q, _ = new(big.Int).SetString("j0eo2kih470xnmi1h48euaf9p3jju0t", 36)
	dsaPubKey.G, _ = new(big.Int).SetString("cgmqmiys12cxkm2ea4kq50xkwrj0hljx2hvq552fwlc6qpxam1rg8nbc4tiyisu4d1g9lze2i0eh1ph98gakbu74tfdjhnae5e21jajqd6dsn27gkgntht135lfjv2v4kiffhcay86ukt1erwvoqku5nq3zksek4xvnox8qran1ej3lhg00m02vmqvp57ddbhblmj3", 36)
	dsaPubKey.Y, _ = new(big.Int).SetString("r6ktcw24rezvnmqnkgd69z578mhcjhxkzipw8kdb1dz686i5u208mh9jau8g3ois3khw63haw8pi3dkh7gmv1mpom5rkgwijiyl40lhrcvda8yfzedsurob6i67a6rrm9181giq7q1c5bby3triiqyoj5ngjm9hjz1j6nj630k9sy3jdg5zj51cyj4765yc5b4xf8k", 36)

	PAUSEPublicKey = packet.NewDSAPublicKey(time.Unix(1044279440, 0), &dsaPubKey)
}
